import "./globals.css";
import Nav from "@/components/Nav";
import TransitionProvider from "@/providers/TransitionProvider";

export const metadata = {
  title: "Block Reveal Effect Page Transition",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
          <TransitionProvider>
            <Nav />
              {children}
          </TransitionProvider>
      </body>
    </html>
  );
}
